@testable import Shell
// import JavaScriptCore
import XCTest

final class GlobTests: XCTestCase {
// func testAssertions() {
//  echo("Testing Bash Glob Algorithm", style: .bold)
//  measure {
//   XCTAssert(matchGlob("a/b/**/c{d,e}/**/xyz.md", "a/b/cd/xyz.md"))
//   XCTAssert(matchGlob("a/b/**/{c,d,e}/**/xyz.md", "a/b/c/xyz.md"))
//   XCTAssert(matchGlob("a/b/**/{c,d,e}/**/xyz.md", "a/b/d/xyz.md"))
//   XCTAssert(matchGlob("a/b/**/{c,d,e}/**/xyz.md", "a/b/e/xyz.md"))
//  }
//  assertFunction(matchGlob)
// }
//
// func testRegexAssertions() {
//  echo("Testing Regex Glob Algorithm", style: .bold)
//  measure {
//   XCTAssert(!matchRegexGlob("a/b/**/c{d,e}/**/xyz.md", "a/b/cd/xyz.md"))
//   XCTAssert(!matchRegexGlob("a/b/**/{c,d,e}/**/xyz.md", "a/b/c/xyz.md"))
//   XCTAssert(!matchRegexGlob("a/b/**/{c,d,e}/**/xyz.md", "a/b/d/xyz.md"))
//   XCTAssert(!matchRegexGlob("a/b/**/{c,d,e}/**/xyz.md", "a/b/e/xyz.md"))
//  }
// }
 // func testPythonAssertions() { assertFunction(matchPythonGlob) }
}

final class WildcardTests: XCTestCase {
 // func testAssertions() { assertFunction(matchWildcard) }
}

// MARK: Algorithms
func matchGlob(_ pattern: String, _ string: String) -> Bool {
 if let results = string.matches(glob: pattern) {
  echo(
   pattern, " [", string.quoted, "] ", "(",
   results.map { range in
    "\"\(string[range.lowerBound ..< range.upperBound])\""
   }
   .joined(separator: ", "),
   ")",
   color: .blue, style: .bold, separator: ""
  )
  return true
 } else {
  echo(
   pattern, " (", string.quoted, ") ", "[]", color: .yellow, style: .bold, separator: ""
  )
  return false
 }
}

/*
 import PythonKit
 let glob2 = Python.import("glob2")

 func matchPythonGlob(_ pattern: String, _ string: String) -> Bool {
  false
 }

 import JavaScriptCore
 func matchNodeGlob(_ pattern: String, _ string: String) -> Bool {
  if let results =
      JSContext()!.evaluateScript(
   """
   var mm = require('micromatch');
   log.console(mm.capture('\(pattern)', '\(string)');
   """
      ).toArray() {
   echo(
    pattern, " [", results.map({ "\($0)" }).joined(separator: ","), "] ",
    color: .blue, style: .bold, separator: ""
   )
   return true
  } else {
   echo(
    pattern, " (", string.quoted, ") ", color: .yellow, style: .bold, separator: ""
   )
   return false
  }
 }
 */
func matchWildcard(_ pattern: String, _ string: String) -> Bool {
 if string.contains(wildcard: pattern) {
  echo(pattern, " [", string.quoted, "] ", color: .blue, style: .bold, separator: "")
  return true
 } else {
  echo(
   pattern, " (", string.quoted, ") ", color: .yellow, style: .bold, separator: ""
  )
  return false
 }
}

/// A handler for testing out different matchers
func assertFunction(_ function: (String, String) -> Bool) {
 XCTAssert(function("abc", "abc"))
 XCTAssert(function("*", "abc"))
 XCTAssert(function("*", ""))
 XCTAssert(function("**", ""))
 XCTAssert(function("*c", "abc"))
 XCTAssert(!function("*b", "abc"))
 XCTAssert(function("a*", "abc"))
 XCTAssert(!function("b*", "abc"))
 XCTAssert(function("a*", "a"))
 XCTAssert(function("*a", "a"))
 XCTAssert(function("a*b*c*d*e*", "axbxcxdxe"))
 XCTAssert(function("a*b*c*d*e*", "axbxcxdxexxx"))
 XCTAssert(function("a*b?c*x", "abxbbxdbxebxczzx"))
 XCTAssert(!function("a*b?c*x", "abxbbxdbxebxczzy"))

 XCTAssert(function("a/*/test", "a/foo/test"))
 XCTAssert(!function("a/*/test", "a/foo/bar/test"))
 XCTAssert(function("a/**/test", "a/foo/test"))
 XCTAssert(function("a/**/test", "a/foo/bar/test"))
 XCTAssert(function("a/**/b/c", "a/foo/bar/b/c"))
 XCTAssert(function("a\\*b", "a*b"))
 XCTAssert(!function("a\\*b", "axb"))

 XCTAssert(function("[abc]", "a"))
 XCTAssert(function("[abc]", "b"))
 XCTAssert(function("[abc]", "c"))
 XCTAssert(!function("[abc]", "d"))
 XCTAssert(function("x[abc]x", "xax"))
 XCTAssert(function("x[abc]x", "xbx"))
 XCTAssert(function("x[abc]x", "xcx"))
 XCTAssert(!function("x[abc]x", "xdx"))
 XCTAssert(!function("x[abc]x", "xay"))
 XCTAssert(function("[?]", "?"))
 XCTAssert(!function("[?]", "a"))
 XCTAssert(function("[*]", "*"))
 XCTAssert(!function("[*]", "a"))

 XCTAssert(function("[a-cx]", "a"))
 XCTAssert(function("[a-cx]", "b"))
 XCTAssert(function("[a-cx]", "c"))
 XCTAssert(!function("[a-cx]", "d"))
 XCTAssert(function("[a-cx]", "x"))

 XCTAssert(!function("[^abc]", "a"))
 XCTAssert(!function("[^abc]", "b"))
 XCTAssert(!function("[^abc]", "c"))
 XCTAssert(function("[^abc]", "d"))
 XCTAssert(!function("[!abc]", "a"))
 XCTAssert(!function("[!abc]", "b"))
 XCTAssert(!function("[!abc]", "c"))
 XCTAssert(function("[!abc]", "d"))
 XCTAssert(function("[\\!]", "!"))

 XCTAssert(function("a*b*[cy]*d*e*", "axbxcxdxexxx"))
 XCTAssert(function("a*b*[cy]*d*e*", "axbxyxdxexxx"))
 XCTAssert(function("a*b*[cy]*d*e*", "axbxxxyxdxexxx"))

 XCTAssert(function("test.{jpg,png}", "test.jpg"))
 XCTAssert(function("test.{jpg,png}", "test.png"))
 XCTAssert(function("test.{j*g,p*g}", "test.jpg"))
 XCTAssert(function("test.{j*g,p*g}", "test.jpxxxg"))
 XCTAssert(function("test.{j*g,p*g}", "test.jxg"))
 XCTAssert(!function("test.{j*g,p*g}", "test.jnt"))
 XCTAssert(function("test.{j*g,j*c}", "test.jnc"))
 XCTAssert(function("test.{jpg,p*g}", "test.png"))
 XCTAssert(function("test.{jpg,p*g}", "test.pxg"))
 XCTAssert(!function("test.{jpg,p*g}", "test.pnt"))
 XCTAssert(function("test.{jpeg,png}", "test.jpeg"))
 XCTAssert(!function("test.{jpeg,png}", "test.jpg"))
 XCTAssert(function("test.{jpeg,png}", "test.png"))
 XCTAssert(function("test.{jp\\,g,png}", "test.jp,g"))
 XCTAssert(!function("test.{jp\\,g,png}", "test.jxg"))
 XCTAssert(function("test/{foo,bar}/baz", "test/foo/baz"))
 XCTAssert(function("test/{foo,bar}/baz", "test/bar/baz"))
 XCTAssert(!function("test/{foo,bar}/baz", "test/baz/baz"))
 XCTAssert(function("test/{foo*,bar*}/baz", "test/foooooo/baz"))
 XCTAssert(function("test/{foo*,bar*}/baz", "test/barrrrr/baz"))
 XCTAssert(function("test/{*foo,*bar}/baz", "test/xxxxfoo/baz"))
 XCTAssert(function("test/{*foo,*bar}/baz", "test/xxxxbar/baz"))
 XCTAssert(function("test/{foo/**,bar}/baz", "test/bar/baz"))
 XCTAssert(!function("test/{foo/**,bar}/baz", "test/bar/test/baz"))

 XCTAssert(!function("*.txt", "some/big/path/to/the/needle.txt"))
 XCTAssert(function("some/**/needle.{js,tsx,mdx,ts,jsx,txt}", "some/a/bigger/path/to/the/crazy/needle.txt"))
 XCTAssert(function("some/**/{a,b,c}/**/needle.txt", "some/foo/a/bigger/path/to/the/crazy/needle.txt"))
 XCTAssert(!function("some/**/{a,b,c}/**/needle.txt", "some/foo/d/bigger/path/to/the/crazy/needle.txt"))

 XCTAssert(function("a/{a{a,b},b}", "a/aa"))
 XCTAssert(function("a/{a{a,b},b}", "a/ab"))
 XCTAssert(!function("a/{a{a,b},b}", "a/ac"))
 XCTAssert(function("a/{a{a,b},b}", "a/b"))
 XCTAssert(!function("a/{a{a,b},b}", "a/c"))
 XCTAssert(function("a/{b,c[}]*}", "a/b"))
 XCTAssert(function("a/{b,c[}]*}", "a/c}xx"))

 // The below tests are based on Bash and micromatch.
 // https://github.com/micromatch/picomatch/blob/master/test/bash.js
 // Converted using the following find and replace regex:
 // find: assert\(([!])?isMatch\('(.*?)', ['"](.*?)['"]\)\)
 // replace:  XCTAssert($1function("$3", "$2"))

 XCTAssert(!function("a*", "*"))
 XCTAssert(!function("a*", "**"))
 XCTAssert(!function("a*", "\\*"))
 XCTAssert(!function("a*", "a/*"))
 XCTAssert(!function("a*", "b"))
 XCTAssert(!function("a*", "bc"))
 XCTAssert(!function("a*", "bcd"))
 XCTAssert(!function("a*", "bdir/"))
 XCTAssert(!function("a*", "Beware"))
 XCTAssert(function("a*", "a"))
 XCTAssert(function("a*", "ab"))
 XCTAssert(function("a*", "abc"))

 XCTAssert(!function("\\a*", "*"))
 XCTAssert(!function("\\a*", "**"))
 XCTAssert(!function("\\a*", "\\*"))

 XCTAssert(function("\\a*", "a"))
 XCTAssert(!function("\\a*", "a/*"))
 XCTAssert(function("\\a*", "abc"))
 XCTAssert(function("\\a*", "abd"))
 XCTAssert(function("\\a*", "abe"))
 XCTAssert(!function("\\a*", "b"))
 XCTAssert(!function("\\a*", "bb"))
 XCTAssert(!function("\\a*", "bcd"))
 XCTAssert(!function("\\a*", "bdir/"))
 XCTAssert(!function("\\a*", "Beware"))
 XCTAssert(!function("\\a*", "c"))
 XCTAssert(!function("\\a*", "ca"))
 XCTAssert(!function("\\a*", "cb"))
 XCTAssert(!function("\\a*", "d"))
 XCTAssert(!function("\\a*", "dd"))
 XCTAssert(!function("\\a*", "de"))

 // bash directories
 XCTAssert(!function("b*/", "*"))
 XCTAssert(!function("b*/", "**"))
 XCTAssert(!function("b*/", "\\*"))
 XCTAssert(!function("b*/", "a"))
 XCTAssert(!function("b*/", "a/*"))
 XCTAssert(!function("b*/", "abc"))
 XCTAssert(!function("b*/", "abd"))
 XCTAssert(!function("b*/", "abe"))
 XCTAssert(!function("b*/", "b"))
 XCTAssert(!function("b*/", "bb"))
 XCTAssert(!function("b*/", "bcd"))
 XCTAssert(function("b*/", "bdir/"))
 XCTAssert(!function("b*/", "Beware"))
 XCTAssert(!function("b*/", "c"))
 XCTAssert(!function("b*/", "ca"))
 XCTAssert(!function("b*/", "cb"))
 XCTAssert(!function("b*/", "d"))
 XCTAssert(!function("b*/", "dd"))
 XCTAssert(!function("b*/", "de"))

 // bash escaping
 XCTAssert(!function("\\^", "*"))
 XCTAssert(!function("\\^", "**"))
 XCTAssert(!function("\\^", "\\*"))
 XCTAssert(!function("\\^", "a"))
 XCTAssert(!function("\\^", "a/*"))
 XCTAssert(!function("\\^", "abc"))
 XCTAssert(!function("\\^", "abd"))
 XCTAssert(!function("\\^", "abe"))
 XCTAssert(!function("\\^", "b"))
 XCTAssert(!function("\\^", "bb"))
 XCTAssert(!function("\\^", "bcd"))
 XCTAssert(!function("\\^", "bdir/"))
 XCTAssert(!function("\\^", "Beware"))
 XCTAssert(!function("\\^", "c"))
 XCTAssert(!function("\\^", "ca"))
 XCTAssert(!function("\\^", "cb"))
 XCTAssert(!function("\\^", "d"))
 XCTAssert(!function("\\^", "dd"))
 XCTAssert(!function("\\^", "de"))

 XCTAssert(function("\\*", "*"))
 //  XCTAssert(function("\\*", "\\*"))
 XCTAssert(!function("\\*", "**"))
 XCTAssert(!function("\\*", "a"))
 XCTAssert(!function("\\*", "a/*"))
 XCTAssert(!function("\\*", "abc"))
 XCTAssert(!function("\\*", "abd"))
 XCTAssert(!function("\\*", "abe"))
 XCTAssert(!function("\\*", "b"))
 XCTAssert(!function("\\*", "bb"))
 XCTAssert(!function("\\*", "bcd"))
 XCTAssert(!function("\\*", "bdir/"))
 XCTAssert(!function("\\*", "Beware"))
 XCTAssert(!function("\\*", "c"))
 XCTAssert(!function("\\*", "ca"))
 XCTAssert(!function("\\*", "cb"))
 XCTAssert(!function("\\*", "d"))
 XCTAssert(!function("\\*", "dd"))
 XCTAssert(!function("\\*", "de"))

 XCTAssert(!function("a\\*", "*"))
 XCTAssert(!function("a\\*", "**"))
 XCTAssert(!function("a\\*", "\\*"))
 XCTAssert(!function("a\\*", "a"))
 XCTAssert(!function("a\\*", "a/*"))
 XCTAssert(!function("a\\*", "abc"))
 XCTAssert(!function("a\\*", "abd"))
 XCTAssert(!function("a\\*", "abe"))
 XCTAssert(!function("a\\*", "b"))
 XCTAssert(!function("a\\*", "bb"))
 XCTAssert(!function("a\\*", "bcd"))
 XCTAssert(!function("a\\*", "bdir/"))
 XCTAssert(!function("a\\*", "Beware"))
 XCTAssert(!function("a\\*", "c"))
 XCTAssert(!function("a\\*", "ca"))
 XCTAssert(!function("a\\*", "cb"))
 XCTAssert(!function("a\\*", "d"))
 XCTAssert(!function("a\\*", "dd"))
 XCTAssert(!function("a\\*", "de"))

 XCTAssert(function("*q*", "aqa"))
 XCTAssert(function("*q*", "aaqaa"))
 XCTAssert(!function("*q*", "*"))
 XCTAssert(!function("*q*", "**"))
 XCTAssert(!function("*q*", "\\*"))
 XCTAssert(!function("*q*", "a"))
 XCTAssert(!function("*q*", "a/*"))
 XCTAssert(!function("*q*", "abc"))
 XCTAssert(!function("*q*", "abd"))
 XCTAssert(!function("*q*", "abe"))
 XCTAssert(!function("*q*", "b"))
 XCTAssert(!function("*q*", "bb"))
 XCTAssert(!function("*q*", "bcd"))
 XCTAssert(!function("*q*", "bdir/"))
 XCTAssert(!function("*q*", "Beware"))
 XCTAssert(!function("*q*", "c"))
 XCTAssert(!function("*q*", "ca"))
 XCTAssert(!function("*q*", "cb"))
 XCTAssert(!function("*q*", "d"))
 XCTAssert(!function("*q*", "dd"))
 XCTAssert(!function("*q*", "de"))

 XCTAssert(function("\\**", "*"))
 XCTAssert(function("\\**", "**"))
 XCTAssert(!function("\\**", "\\*"))
 XCTAssert(!function("\\**", "a"))
 XCTAssert(!function("\\**", "a/*"))
 XCTAssert(!function("\\**", "abc"))
 XCTAssert(!function("\\**", "abd"))
 XCTAssert(!function("\\**", "abe"))
 XCTAssert(!function("\\**", "b"))
 XCTAssert(!function("\\**", "bb"))
 XCTAssert(!function("\\**", "bcd"))
 XCTAssert(!function("\\**", "bdir/"))
 XCTAssert(!function("\\**", "Beware"))
 XCTAssert(!function("\\**", "c"))
 XCTAssert(!function("\\**", "ca"))
 XCTAssert(!function("\\**", "cb"))
 XCTAssert(!function("\\**", "d"))
 XCTAssert(!function("\\**", "dd"))
 XCTAssert(!function("\\**", "de"))

 // bash classes
 XCTAssert(!function("a*[^c]", "*"))
 XCTAssert(!function("a*[^c]", "**"))
 XCTAssert(!function("a*[^c]", "\\*"))
 XCTAssert(!function("a*[^c]", "a"))
 XCTAssert(!function("a*[^c]", "a/*"))
 XCTAssert(!function("a*[^c]", "abc"))
 XCTAssert(function("a*[^c]", "abd"))
 XCTAssert(function("a*[^c]", "abe"))
 XCTAssert(!function("a*[^c]", "b"))
 XCTAssert(!function("a*[^c]", "bb"))
 XCTAssert(!function("a*[^c]", "bcd"))
 XCTAssert(!function("a*[^c]", "bdir/"))
 XCTAssert(!function("a*[^c]", "Beware"))
 XCTAssert(!function("a*[^c]", "c"))
 XCTAssert(!function("a*[^c]", "ca"))
 XCTAssert(!function("a*[^c]", "cb"))
 XCTAssert(!function("a*[^c]", "d"))
 XCTAssert(!function("a*[^c]", "dd"))
 XCTAssert(!function("a*[^c]", "de"))
 XCTAssert(!function("a*[^c]", "baz"))
 XCTAssert(!function("a*[^c]", "bzz"))
 XCTAssert(!function("a*[^c]", "BZZ"))
 XCTAssert(!function("a*[^c]", "beware"))
 XCTAssert(!function("a*[^c]", "BewAre"))

 XCTAssert(function("a[X-]b", "a-b"))
 XCTAssert(function("a[X-]b", "aXb"))

 XCTAssert(!function("[a-y]*[^c]", "*"))
 XCTAssert(function("[a-y]*[^c]", "a*"))
 XCTAssert(!function("[a-y]*[^c]", "**"))
 XCTAssert(!function("[a-y]*[^c]", "\\*"))
 XCTAssert(!function("[a-y]*[^c]", "a"))
 XCTAssert(function("[a-y]*[^c]", "a123b"))
 XCTAssert(!function("[a-y]*[^c]", "a123c"))
 XCTAssert(function("[a-y]*[^c]", "ab"))
 XCTAssert(!function("[a-y]*[^c]", "a/*"))
 XCTAssert(!function("[a-y]*[^c]", "abc"))
 XCTAssert(function("[a-y]*[^c]", "abd"))
 XCTAssert(function("[a-y]*[^c]", "abe"))
 XCTAssert(!function("[a-y]*[^c]", "b"))
 XCTAssert(function("[a-y]*[^c]", "bd"))
 XCTAssert(function("[a-y]*[^c]", "bb"))
 XCTAssert(function("[a-y]*[^c]", "bcd"))
 XCTAssert(function("[a-y]*[^c]", "bdir/"))
 XCTAssert(!function("[a-y]*[^c]", "Beware"))
 XCTAssert(!function("[a-y]*[^c]", "c"))
 XCTAssert(function("[a-y]*[^c]", "ca"))
 XCTAssert(function("[a-y]*[^c]", "cb"))
 XCTAssert(!function("[a-y]*[^c]", "d"))
 XCTAssert(function("[a-y]*[^c]", "dd"))
 XCTAssert(function("[a-y]*[^c]", "dd"))
 XCTAssert(function("[a-y]*[^c]", "dd"))
 XCTAssert(function("[a-y]*[^c]", "de"))
 XCTAssert(function("[a-y]*[^c]", "baz"))
 XCTAssert(function("[a-y]*[^c]", "bzz"))
 XCTAssert(function("[a-y]*[^c]", "bzz"))
 //  XCTAssert(!isMatch('bzz', '[a-y]*[^c]', { regex: true }))
 XCTAssert(!function("[a-y]*[^c]", "BZZ"))
 XCTAssert(function("[a-y]*[^c]", "beware"))
 XCTAssert(!function("[a-y]*[^c]", "BewAre"))

 XCTAssert(function("a\\*b/*", "a*b/ooo"))
 XCTAssert(function("a\\*?/*", "a*b/ooo"))

 XCTAssert(!function("a[b]c", "*"))
 XCTAssert(!function("a[b]c", "**"))
 XCTAssert(!function("a[b]c", "\\*"))
 XCTAssert(!function("a[b]c", "a"))
 XCTAssert(!function("a[b]c", "a/*"))
 XCTAssert(function("a[b]c", "abc"))
 XCTAssert(!function("a[b]c", "abd"))
 XCTAssert(!function("a[b]c", "abe"))
 XCTAssert(!function("a[b]c", "b"))
 XCTAssert(!function("a[b]c", "bb"))
 XCTAssert(!function("a[b]c", "bcd"))
 XCTAssert(!function("a[b]c", "bdir/"))
 XCTAssert(!function("a[b]c", "Beware"))
 XCTAssert(!function("a[b]c", "c"))
 XCTAssert(!function("a[b]c", "ca"))
 XCTAssert(!function("a[b]c", "cb"))
 XCTAssert(!function("a[b]c", "d"))
 XCTAssert(!function("a[b]c", "dd"))
 XCTAssert(!function("a[b]c", "de"))
 XCTAssert(!function("a[b]c", "baz"))
 XCTAssert(!function("a[b]c", "bzz"))
 XCTAssert(!function("a[b]c", "BZZ"))
 XCTAssert(!function("a[b]c", "beware"))
 XCTAssert(!function("a[b]c", "BewAre"))

 XCTAssert(!function("a[\"b\"]c", "*"))
 XCTAssert(!function("a[\"b\"]c", "**"))
 XCTAssert(!function("a[\"b\"]c", "\\*"))
 XCTAssert(!function("a[\"b\"]c", "a"))
 XCTAssert(!function("a[\"b\"]c", "a/*"))
 XCTAssert(function("a[\"b\"]c", "abc"))
 XCTAssert(!function("a[\"b\"]c", "abd"))
 XCTAssert(!function("a[\"b\"]c", "abe"))
 XCTAssert(!function("a[\"b\"]c", "b"))
 XCTAssert(!function("a[\"b\"]c", "bb"))
 XCTAssert(!function("a[\"b\"]c", "bcd"))
 XCTAssert(!function("a[\"b\"]c", "bdir/"))
 XCTAssert(!function("a[\"b\"]c", "Beware"))
 XCTAssert(!function("a[\"b\"]c", "c"))
 XCTAssert(!function("a[\"b\"]c", "ca"))
 XCTAssert(!function("a[\"b\"]c", "cb"))
 XCTAssert(!function("a[\"b\"]c", "d"))
 XCTAssert(!function("a[\"b\"]c", "dd"))
 XCTAssert(!function("a[\"b\"]c", "de"))
 XCTAssert(!function("a[\"b\"]c", "baz"))
 XCTAssert(!function("a[\"b\"]c", "bzz"))
 XCTAssert(!function("a[\"b\"]c", "BZZ"))
 XCTAssert(!function("a[\"b\"]c", "beware"))
 XCTAssert(!function("a[\"b\"]c", "BewAre"))

 XCTAssert(!function("a[\\\\b]c", "*"))
 XCTAssert(!function("a[\\\\b]c", "**"))
 XCTAssert(!function("a[\\\\b]c", "\\*"))
 XCTAssert(!function("a[\\\\b]c", "a"))
 XCTAssert(!function("a[\\\\b]c", "a/*"))
 XCTAssert(function("a[\\\\b]c", "abc"))
 XCTAssert(!function("a[\\\\b]c", "abd"))
 XCTAssert(!function("a[\\\\b]c", "abe"))
 XCTAssert(!function("a[\\\\b]c", "b"))
 XCTAssert(!function("a[\\\\b]c", "bb"))
 XCTAssert(!function("a[\\\\b]c", "bcd"))
 XCTAssert(!function("a[\\\\b]c", "bdir/"))
 XCTAssert(!function("a[\\\\b]c", "Beware"))
 XCTAssert(!function("a[\\\\b]c", "c"))
 XCTAssert(!function("a[\\\\b]c", "ca"))
 XCTAssert(!function("a[\\\\b]c", "cb"))
 XCTAssert(!function("a[\\\\b]c", "d"))
 XCTAssert(!function("a[\\\\b]c", "dd"))
 XCTAssert(!function("a[\\\\b]c", "de"))
 XCTAssert(!function("a[\\\\b]c", "baz"))
 XCTAssert(!function("a[\\\\b]c", "bzz"))
 XCTAssert(!function("a[\\\\b]c", "BZZ"))
 XCTAssert(!function("a[\\\\b]c", "beware"))
 XCTAssert(!function("a[\\\\b]c", "BewAre"))

 XCTAssert(!function("a[\\b]c", "*"))
 XCTAssert(!function("a[\\b]c", "**"))
 XCTAssert(!function("a[\\b]c", "\\*"))
 XCTAssert(!function("a[\\b]c", "a"))
 XCTAssert(!function("a[\\b]c", "a/*"))
 XCTAssert(!function("a[\\b]c", "abc"))
 XCTAssert(!function("a[\\b]c", "abd"))
 XCTAssert(!function("a[\\b]c", "abe"))
 XCTAssert(!function("a[\\b]c", "b"))
 XCTAssert(!function("a[\\b]c", "bb"))
 XCTAssert(!function("a[\\b]c", "bcd"))
 XCTAssert(!function("a[\\b]c", "bdir/"))
 XCTAssert(!function("a[\\b]c", "Beware"))
 XCTAssert(!function("a[\\b]c", "c"))
 XCTAssert(!function("a[\\b]c", "ca"))
 XCTAssert(!function("a[\\b]c", "cb"))
 XCTAssert(!function("a[\\b]c", "d"))
 XCTAssert(!function("a[\\b]c", "dd"))
 XCTAssert(!function("a[\\b]c", "de"))
 XCTAssert(!function("a[\\b]c", "baz"))
 XCTAssert(!function("a[\\b]c", "bzz"))
 XCTAssert(!function("a[\\b]c", "BZZ"))
 XCTAssert(!function("a[\\b]c", "beware"))
 XCTAssert(!function("a[\\b]c", "BewAre"))

 XCTAssert(!function("a[b-d]c", "*"))
 XCTAssert(!function("a[b-d]c", "**"))
 XCTAssert(!function("a[b-d]c", "\\*"))
 XCTAssert(!function("a[b-d]c", "a"))
 XCTAssert(!function("a[b-d]c", "a/*"))
 XCTAssert(function("a[b-d]c", "abc"))
 XCTAssert(!function("a[b-d]c", "abd"))
 XCTAssert(!function("a[b-d]c", "abe"))
 XCTAssert(!function("a[b-d]c", "b"))
 XCTAssert(!function("a[b-d]c", "bb"))
 XCTAssert(!function("a[b-d]c", "bcd"))
 XCTAssert(!function("a[b-d]c", "bdir/"))
 XCTAssert(!function("a[b-d]c", "Beware"))
 XCTAssert(!function("a[b-d]c", "c"))
 XCTAssert(!function("a[b-d]c", "ca"))
 XCTAssert(!function("a[b-d]c", "cb"))
 XCTAssert(!function("a[b-d]c", "d"))
 XCTAssert(!function("a[b-d]c", "dd"))
 XCTAssert(!function("a[b-d]c", "de"))
 XCTAssert(!function("a[b-d]c", "baz"))
 XCTAssert(!function("a[b-d]c", "bzz"))
 XCTAssert(!function("a[b-d]c", "BZZ"))
 XCTAssert(!function("a[b-d]c", "beware"))
 XCTAssert(!function("a[b-d]c", "BewAre"))

 XCTAssert(!function("a?c", "*"))
 XCTAssert(!function("a?c", "**"))
 XCTAssert(!function("a?c", "\\*"))
 XCTAssert(!function("a?c", "a"))
 XCTAssert(!function("a?c", "a/*"))
 XCTAssert(function("a?c", "abc"))
 XCTAssert(!function("a?c", "abd"))
 XCTAssert(!function("a?c", "abe"))
 XCTAssert(!function("a?c", "b"))
 XCTAssert(!function("a?c", "bb"))
 XCTAssert(!function("a?c", "bcd"))
 XCTAssert(!function("a?c", "bdir/"))
 XCTAssert(!function("a?c", "Beware"))
 XCTAssert(!function("a?c", "c"))
 XCTAssert(!function("a?c", "ca"))
 XCTAssert(!function("a?c", "cb"))
 XCTAssert(!function("a?c", "d"))
 XCTAssert(!function("a?c", "dd"))
 XCTAssert(!function("a?c", "de"))
 XCTAssert(!function("a?c", "baz"))
 XCTAssert(!function("a?c", "bzz"))
 XCTAssert(!function("a?c", "BZZ"))
 XCTAssert(!function("a?c", "beware"))
 XCTAssert(!function("a?c", "BewAre"))

 XCTAssert(function("*/man*/bash.*", "man/man1/bash.1"))

 XCTAssert(function("[^a-c]*", "*"))
 XCTAssert(function("[^a-c]*", "**"))
 XCTAssert(!function("[^a-c]*", "a"))
 XCTAssert(!function("[^a-c]*", "a/*"))
 XCTAssert(!function("[^a-c]*", "abc"))
 XCTAssert(!function("[^a-c]*", "abd"))
 XCTAssert(!function("[^a-c]*", "abe"))
 XCTAssert(!function("[^a-c]*", "b"))
 XCTAssert(!function("[^a-c]*", "bb"))
 XCTAssert(!function("[^a-c]*", "bcd"))
 XCTAssert(!function("[^a-c]*", "bdir/"))
 XCTAssert(function("[^a-c]*", "Beware"))
 XCTAssert(function("[^a-c]*", "Beware"))
 XCTAssert(!function("[^a-c]*", "c"))
 XCTAssert(!function("[^a-c]*", "ca"))
 XCTAssert(!function("[^a-c]*", "cb"))
 XCTAssert(function("[^a-c]*", "d"))
 XCTAssert(function("[^a-c]*", "dd"))
 XCTAssert(function("[^a-c]*", "de"))
 XCTAssert(!function("[^a-c]*", "baz"))
 XCTAssert(!function("[^a-c]*", "bzz"))
 XCTAssert(function("[^a-c]*", "BZZ"))
 XCTAssert(!function("[^a-c]*", "beware"))
 XCTAssert(function("[^a-c]*", "BewAre"))

 // bash wildmatch
 XCTAssert(!function("a[]-]b", "aab"))
 XCTAssert(!function("[ten]", "ten"))
 XCTAssert(function("]", "]"))
 XCTAssert(function("a[]-]b", "a-b"))
 XCTAssert(function("a[]-]b", "a]b"))
 XCTAssert(function("a[]]b", "a]b"))
 XCTAssert(function("a[\\]a\\-]b", "aab"))
 XCTAssert(function("t[a-g]n", "ten"))
 XCTAssert(function("t[^a-g]n", "ton"))

 // bash slashmatch
 //  XCTAssert(!function("f[^eiu][^eiu][^eiu][^eiu][^eiu]r", "foo/bar"))
 XCTAssert(function("foo[/]bar", "foo/bar"))
 XCTAssert(function("f[^eiu][^eiu][^eiu][^eiu][^eiu]r", "foo-bar"))

 // bash extra stars
 XCTAssert(!function("a**c", "bbc"))
 XCTAssert(function("a**c", "abc"))
 XCTAssert(!function("a**c", "bbd"))

 XCTAssert(!function("a***c", "bbc"))
 XCTAssert(function("a***c", "abc"))
 XCTAssert(!function("a***c", "bbd"))

 XCTAssert(!function("a*****?c", "bbc"))
 XCTAssert(function("a*****?c", "abc"))
 XCTAssert(!function("a*****?c", "bbc"))

 XCTAssert(function("?*****??", "bbc"))
 XCTAssert(function("?*****??", "abc"))

 XCTAssert(function("*****??", "bbc"))
 XCTAssert(function("*****??", "abc"))

 XCTAssert(function("?*****?c", "bbc"))
 XCTAssert(function("?*****?c", "abc"))

 XCTAssert(function("?***?****c", "bbc"))
 XCTAssert(function("?***?****c", "abc"))
 XCTAssert(!function("?***?****c", "bbd"))

 XCTAssert(function("?***?****?", "bbc"))
 XCTAssert(function("?***?****?", "abc"))

 XCTAssert(function("?***?****", "bbc"))
 XCTAssert(function("?***?****", "abc"))

 XCTAssert(function("*******c", "bbc"))
 XCTAssert(function("*******c", "abc"))

 XCTAssert(function("*******?", "bbc"))
 XCTAssert(function("*******?", "abc"))

 XCTAssert(function("a*cd**?**??k", "abcdecdhjk"))
 XCTAssert(function("a**?**cd**?**??k", "abcdecdhjk"))
 XCTAssert(function("a**?**cd**?**??k***", "abcdecdhjk"))
 XCTAssert(function("a**?**cd**?**??***k", "abcdecdhjk"))
 XCTAssert(function("a**?**cd**?**??***k**", "abcdecdhjk"))
 XCTAssert(function("a****c**?**??*****", "abcdecdhjk"))

 // stars
 XCTAssert(!function("*.js", "a/b/c/z.js"))
 XCTAssert(!function("*.js", "a/b/z.js"))
 XCTAssert(!function("*.js", "a/z.js"))
 XCTAssert(function("*.js", "z.js"))

 //  XCTAssert(!function("*/*", "a/.ab"))
 //  XCTAssert(!function("*", ".ab"))

 XCTAssert(function("z*.js", "z.js"))
 XCTAssert(function("*/*", "a/z"))
 XCTAssert(function("*/z*.js", "a/z.js"))
 XCTAssert(function("a/z*.js", "a/z.js"))

 XCTAssert(function("*", "ab"))
 XCTAssert(function("*", "abc"))

 XCTAssert(!function("f*", "bar"))
 XCTAssert(!function("*r", "foo"))
 XCTAssert(!function("b*", "foo"))
 XCTAssert(!function("*", "foo/bar"))
 XCTAssert(function("*c", "abc"))
 XCTAssert(function("a*", "abc"))
 XCTAssert(function("a*c", "abc"))
 XCTAssert(function("*r", "bar"))
 XCTAssert(function("b*", "bar"))
 XCTAssert(function("f*", "foo"))

 XCTAssert(function("*abc*", "one abc two"))
 XCTAssert(function("a*b", "a         b"))

 XCTAssert(!function("*a*", "foo"))
 XCTAssert(function("*a*", "bar"))
 XCTAssert(function("*abc*", "oneabctwo"))
 XCTAssert(!function("*-bc-*", "a-b.c-d"))
 XCTAssert(function("*-*.*-*", "a-b.c-d"))
 XCTAssert(function("*-b*c-*", "a-b.c-d"))
 XCTAssert(function("*-b.c-*", "a-b.c-d"))
 XCTAssert(function("*.*", "a-b.c-d"))
 XCTAssert(function("*.*-*", "a-b.c-d"))
 XCTAssert(function("*.*-d", "a-b.c-d"))
 XCTAssert(function("*.c-*", "a-b.c-d"))
 XCTAssert(function("*b.*d", "a-b.c-d"))
 XCTAssert(function("a*.c*", "a-b.c-d"))
 XCTAssert(function("a-*.*-d", "a-b.c-d"))
 XCTAssert(function("*.*", "a.b"))
 XCTAssert(function("*.b", "a.b"))
 XCTAssert(function("a.*", "a.b"))
 XCTAssert(function("a.b", "a.b"))

 XCTAssert(!function("**-bc-**", "a-b.c-d"))
 XCTAssert(function("**-**.**-**", "a-b.c-d"))
 XCTAssert(function("**-b**c-**", "a-b.c-d"))
 XCTAssert(function("**-b.c-**", "a-b.c-d"))
 XCTAssert(function("**.**", "a-b.c-d"))
 XCTAssert(function("**.**-**", "a-b.c-d"))
 XCTAssert(function("**.**-d", "a-b.c-d"))
 XCTAssert(function("**.c-**", "a-b.c-d"))
 XCTAssert(function("**b.**d", "a-b.c-d"))
 XCTAssert(function("a**.c**", "a-b.c-d"))
 XCTAssert(function("a-**.**-d", "a-b.c-d"))
 XCTAssert(function("**.**", "a.b"))
 XCTAssert(function("**.b", "a.b"))
 XCTAssert(function("a.**", "a.b"))
 XCTAssert(function("a.b", "a.b"))

 XCTAssert(function("*/*", "/ab"))
 XCTAssert(function(".", "."))
 XCTAssert(!function("a/", "a/.b"))
 XCTAssert(function("/*", "/ab"))
 XCTAssert(function("/??", "/ab"))
 XCTAssert(function("/?b", "/ab"))
 XCTAssert(function("/*", "/cd"))
 XCTAssert(function("a", "a"))
 XCTAssert(function("a/.*", "a/.b"))
 XCTAssert(function("?/?", "a/b"))
 XCTAssert(function("a/**/j/**/z/*.md", "a/b/c/d/e/j/n/p/o/z/c.md"))
 XCTAssert(function("a/**/z/*.md", "a/b/c/d/e/z/c.md"))
 XCTAssert(function("a/b/c/*.md", "a/b/c/xyz.md"))
 XCTAssert(function("a/b/c/*.md", "a/b/c/xyz.md"))
 XCTAssert(function("a/*/z/.a", "a/b/z/.a"))
 XCTAssert(!function("bz", "a/b/z/.a"))
 XCTAssert(function("a/**/c/*.md", "a/bb.bb/aa/b.b/aa/c/xyz.md"))
 XCTAssert(function("a/**/c/*.md", "a/bb.bb/aa/bb/aa/c/xyz.md"))
 XCTAssert(function("a/*/c/*.md", "a/bb.bb/c/xyz.md"))
 XCTAssert(function("a/*/c/*.md", "a/bb/c/xyz.md"))
 XCTAssert(function("a/*/c/*.md", "a/bbbb/c/xyz.md"))
 XCTAssert(function("*", "aaa"))
 XCTAssert(function("*", "ab"))
 XCTAssert(function("ab", "ab"))

 XCTAssert(!function("*/*/*", "aaa"))
 XCTAssert(!function("*/*/*", "aaa/bb/aa/rr"))
 XCTAssert(!function("aaa*", "aaa/bba/ccc"))
 //  XCTAssert(!function("aaa**", "aaa/bba/ccc"))
 XCTAssert(!function("aaa/*", "aaa/bba/ccc"))
 XCTAssert(!function("aaa/*ccc", "aaa/bba/ccc"))
 XCTAssert(!function("aaa/*z", "aaa/bba/ccc"))
 XCTAssert(!function("*/*/*", "aaa/bbb"))
 XCTAssert(!function("*/*jk*/*i", "ab/zzz/ejkl/hi"))
 XCTAssert(function("*/*/*", "aaa/bba/ccc"))
 XCTAssert(function("aaa/**", "aaa/bba/ccc"))
 XCTAssert(function("aaa/*", "aaa/bbb"))
 XCTAssert(function("*/*z*/*/*i", "ab/zzz/ejkl/hi"))
 XCTAssert(function("*j*i", "abzzzejklhi"))

 XCTAssert(function("*", "a"))
 XCTAssert(function("*", "b"))
 XCTAssert(!function("*", "a/a"))
 XCTAssert(!function("*", "a/a/a"))
 XCTAssert(!function("*", "a/a/b"))
 XCTAssert(!function("*", "a/a/a/a"))
 XCTAssert(!function("*", "a/a/a/a/a"))

 XCTAssert(!function("*/*", "a"))
 XCTAssert(function("*/*", "a/a"))
 XCTAssert(!function("*/*", "a/a/a"))

 XCTAssert(!function("*/*/*", "a"))
 XCTAssert(!function("*/*/*", "a/a"))
 XCTAssert(function("*/*/*", "a/a/a"))
 XCTAssert(!function("*/*/*", "a/a/a/a"))

 XCTAssert(!function("*/*/*/*", "a"))
 XCTAssert(!function("*/*/*/*", "a/a"))
 XCTAssert(!function("*/*/*/*", "a/a/a"))
 XCTAssert(function("*/*/*/*", "a/a/a/a"))
 XCTAssert(!function("*/*/*/*", "a/a/a/a/a"))

 XCTAssert(!function("*/*/*/*/*", "a"))
 XCTAssert(!function("*/*/*/*/*", "a/a"))
 XCTAssert(!function("*/*/*/*/*", "a/a/a"))
 XCTAssert(!function("*/*/*/*/*", "a/a/b"))
 XCTAssert(!function("*/*/*/*/*", "a/a/a/a"))
 XCTAssert(function("*/*/*/*/*", "a/a/a/a/a"))
 XCTAssert(!function("*/*/*/*/*", "a/a/a/a/a/a"))

 XCTAssert(!function("a/*", "a"))
 XCTAssert(function("a/*", "a/a"))
 XCTAssert(!function("a/*", "a/a/a"))
 XCTAssert(!function("a/*", "a/a/a/a"))
 XCTAssert(!function("a/*", "a/a/a/a/a"))

 XCTAssert(!function("a/*/*", "a"))
 XCTAssert(!function("a/*/*", "a/a"))
 XCTAssert(function("a/*/*", "a/a/a"))
 XCTAssert(!function("a/*/*", "b/a/a"))
 XCTAssert(!function("a/*/*", "a/a/a/a"))
 XCTAssert(!function("a/*/*", "a/a/a/a/a"))

 XCTAssert(!function("a/*/*/*", "a"))
 XCTAssert(!function("a/*/*/*", "a/a"))
 XCTAssert(!function("a/*/*/*", "a/a/a"))
 XCTAssert(function("a/*/*/*", "a/a/a/a"))
 XCTAssert(!function("a/*/*/*", "a/a/a/a/a"))

 XCTAssert(!function("a/*/*/*/*", "a"))
 XCTAssert(!function("a/*/*/*/*", "a/a"))
 XCTAssert(!function("a/*/*/*/*", "a/a/a"))
 XCTAssert(!function("a/*/*/*/*", "a/a/b"))
 XCTAssert(!function("a/*/*/*/*", "a/a/a/a"))
 XCTAssert(function("a/*/*/*/*", "a/a/a/a/a"))

 XCTAssert(!function("a/*/a", "a"))
 XCTAssert(!function("a/*/a", "a/a"))
 XCTAssert(function("a/*/a", "a/a/a"))
 XCTAssert(!function("a/*/a", "a/a/b"))
 XCTAssert(!function("a/*/a", "a/a/a/a"))
 XCTAssert(!function("a/*/a", "a/a/a/a/a"))

 XCTAssert(!function("a/*/b", "a"))
 XCTAssert(!function("a/*/b", "a/a"))
 XCTAssert(!function("a/*/b", "a/a/a"))
 XCTAssert(function("a/*/b", "a/a/b"))
 XCTAssert(!function("a/*/b", "a/a/a/a"))
 XCTAssert(!function("a/*/b", "a/a/a/a/a"))

 XCTAssert(!function("*/**/a", "a"))
 XCTAssert(!function("*/**/a", "a/a/b"))
 XCTAssert(function("*/**/a", "a/a"))
 XCTAssert(function("*/**/a", "a/a/a"))
 XCTAssert(function("*/**/a", "a/a/a/a"))
 XCTAssert(function("*/**/a", "a/a/a/a/a"))

 XCTAssert(!function("*/", "a"))
 XCTAssert(!function("*/*", "a"))
 XCTAssert(!function("a/*", "a"))
 //  XCTAssert(!function("*/*", "a/"))
 //  XCTAssert(!function("a/*", "a/"))
 XCTAssert(!function("*", "a/a"))
 XCTAssert(!function("*/", "a/a"))
 XCTAssert(!function("*/", "a/x/y"))
 XCTAssert(!function("*/*", "a/x/y"))
 XCTAssert(!function("a/*", "a/x/y"))
 //  XCTAssert(function("*", "a/"))
 XCTAssert(function("*", "a"))
 XCTAssert(function("*/", "a/"))
 XCTAssert(function("*{,/}", "a/"))
 XCTAssert(function("*/*", "a/a"))
 XCTAssert(function("a/*", "a/a"))

 XCTAssert(!function("a/**/*.txt", "a.txt"))
 XCTAssert(function("a/**/*.txt", "a/x/y.txt"))
 XCTAssert(!function("a/**/*.txt", "a/x/y/z"))

 XCTAssert(!function("a/*.txt", "a.txt"))
 XCTAssert(function("a/*.txt", "a/b.txt"))
 XCTAssert(!function("a/*.txt", "a/x/y.txt"))
 XCTAssert(!function("a/*.txt", "a/x/y/z"))

 XCTAssert(function("a*.txt", "a.txt"))
 XCTAssert(!function("a*.txt", "a/b.txt"))
 XCTAssert(!function("a*.txt", "a/x/y.txt"))
 XCTAssert(!function("a*.txt", "a/x/y/z"))

 XCTAssert(function("*.txt", "a.txt"))
 XCTAssert(!function("*.txt", "a/b.txt"))
 XCTAssert(!function("*.txt", "a/x/y.txt"))
 XCTAssert(!function("*.txt", "a/x/y/z"))

 XCTAssert(!function("a*", "a/b"))
 XCTAssert(!function("a/**/b", "a/a/bb"))
 XCTAssert(!function("a/**/b", "a/bb"))

 XCTAssert(!function("*/**", "foo"))
 XCTAssert(!function("**/", "foo/bar"))
 XCTAssert(!function("**/*/", "foo/bar"))
 XCTAssert(!function("*/*/", "foo/bar"))

 XCTAssert(function("**/..", "/home/foo/.."))
 XCTAssert(function("**/a", "a"))
 XCTAssert(function("**", "a/a"))
 XCTAssert(function("a/**", "a/a"))
 XCTAssert(function("a/**", "a/"))
 //  XCTAssert(function("a/**", "a"))
 XCTAssert(!function("**/", "a/a"))
 //  XCTAssert(function("**/a/**", "a"))
 //  XCTAssert(function("a/**", "a"))
 XCTAssert(!function("**/", "a/a"))
 XCTAssert(function("*/**/a", "a/a"))
 //  XCTAssert(function("a/**", "a"))
 XCTAssert(function("*/**", "foo/"))
 XCTAssert(function("**/*", "foo/bar"))
 XCTAssert(function("*/*", "foo/bar"))
 XCTAssert(function("*/**", "foo/bar"))
 XCTAssert(function("**/", "foo/bar/"))
 //  XCTAssert(function("**/*", "foo/bar/"))
 XCTAssert(function("**/*/", "foo/bar/"))
 XCTAssert(function("*/**", "foo/bar/"))
 XCTAssert(function("*/*/", "foo/bar/"))

 XCTAssert(!function("*/foo", "bar/baz/foo"))
 XCTAssert(!function("**/bar/*", "deep/foo/bar"))
 XCTAssert(!function("*/bar/**", "deep/foo/bar/baz/x"))
 XCTAssert(!function("/*", "ef"))
 XCTAssert(!function("foo?bar", "foo/bar"))
 XCTAssert(!function("**/bar*", "foo/bar/baz"))
 //  XCTAssert(!function("**/bar**", "foo/bar/baz"))
 XCTAssert(!function("foo**bar", "foo/baz/bar"))
 XCTAssert(!function("foo*bar", "foo/baz/bar"))
 //  XCTAssert(function("foo/**", "foo"))
 XCTAssert(function("/*", "/ab"))
 XCTAssert(function("/*", "/cd"))
 XCTAssert(function("/*", "/ef"))
 XCTAssert(function("a/**/j/**/z/*.md", "a/b/j/c/z/x.md"))
 XCTAssert(function("a/**/j/**/z/*.md", "a/j/z/x.md"))

 XCTAssert(function("**/foo", "bar/baz/foo"))
 XCTAssert(function("**/bar/*", "deep/foo/bar/baz"))
 XCTAssert(function("**/bar/**", "deep/foo/bar/baz/"))
 XCTAssert(function("**/bar/*/*", "deep/foo/bar/baz/x"))
 XCTAssert(function("foo/**/**/bar", "foo/b/a/z/bar"))
 XCTAssert(function("foo/**/bar", "foo/b/a/z/bar"))
 XCTAssert(function("foo/**/**/bar", "foo/bar"))
 XCTAssert(function("foo/**/bar", "foo/bar"))
 XCTAssert(function("*/bar/**", "foo/bar/baz/x"))
 XCTAssert(function("foo/**/**/bar", "foo/baz/bar"))
 XCTAssert(function("foo/**/bar", "foo/baz/bar"))
 XCTAssert(function("**/foo", "XXX/foo"))

 // globstars
 XCTAssert(function("**/*.js", "a/b/c/d.js"))
 XCTAssert(function("**/*.js", "a/b/c.js"))
 XCTAssert(function("**/*.js", "a/b.js"))
 XCTAssert(function("a/b/**/*.js", "a/b/c/d/e/f.js"))
 XCTAssert(function("a/b/**/*.js", "a/b/c/d/e.js"))
 XCTAssert(function("a/b/c/**/*.js", "a/b/c/d.js"))
 XCTAssert(function("a/b/**/*.js", "a/b/c/d.js"))
 XCTAssert(function("a/b/**/*.js", "a/b/d.js"))
 XCTAssert(!function("a/b/**/*.js", "a/d.js"))
 XCTAssert(!function("a/b/**/*.js", "d.js"))

 XCTAssert(!function("**c", "a/b/c"))
 XCTAssert(!function("a/**c", "a/b/c"))
 XCTAssert(!function("a/**z", "a/b/c"))
 XCTAssert(!function("a/**b**/c", "a/b/c/b/c"))
 XCTAssert(!function("a/b/c**/*.js", "a/b/c/d/e.js"))
 XCTAssert(function("a/**/b/**/c", "a/b/c/b/c"))
 XCTAssert(function("a/**b**/c", "a/aba/c"))
 XCTAssert(function("a/**b**/c", "a/b/c"))
 XCTAssert(function("a/b/c**/*.js", "a/b/c/d.js"))

 XCTAssert(!function("a/**/*", "a"))
 XCTAssert(!function("a/**/**/*", "a"))
 XCTAssert(!function("a/**/**/**/*", "a"))
 XCTAssert(!function("**/a", "a/"))
 XCTAssert(!function("a/**/*", "a/"))
 XCTAssert(!function("a/**/**/*", "a/"))
 XCTAssert(!function("a/**/**/**/*", "a/"))
 XCTAssert(!function("**/a", "a/b"))
 XCTAssert(!function("a/**/j/**/z/*.md", "a/b/c/j/e/z/c.txt"))
 XCTAssert(!function("a/**/b", "a/bb"))
 XCTAssert(!function("**/a", "a/c"))
 XCTAssert(!function("**/a", "a/b"))
 XCTAssert(!function("**/a", "a/x/y"))
 XCTAssert(!function("**/a", "a/b/c/d"))
 XCTAssert(function("**", "a"))
 XCTAssert(function("**/a", "a"))
 //  XCTAssert(function("a/**", "a"))
 XCTAssert(function("**", "a/"))
 XCTAssert(function("**/a/**", "a/"))
 XCTAssert(function("a/**", "a/"))
 XCTAssert(function("a/**/**", "a/"))
 XCTAssert(function("**/a", "a/a"))
 XCTAssert(function("**", "a/b"))
 XCTAssert(function("*/*", "a/b"))
 XCTAssert(function("a/**", "a/b"))
 XCTAssert(function("a/**/*", "a/b"))
 XCTAssert(function("a/**/**/*", "a/b"))
 XCTAssert(function("a/**/**/**/*", "a/b"))
 XCTAssert(function("a/**/b", "a/b"))
 XCTAssert(function("**", "a/b/c"))
 XCTAssert(function("**/*", "a/b/c"))
 XCTAssert(function("**/**", "a/b/c"))
 XCTAssert(function("*/**", "a/b/c"))
 XCTAssert(function("a/**", "a/b/c"))
 XCTAssert(function("a/**/*", "a/b/c"))
 XCTAssert(function("a/**/**/*", "a/b/c"))
 XCTAssert(function("a/**/**/**/*", "a/b/c"))
 XCTAssert(function("**", "a/b/c/d"))
 XCTAssert(function("a/**", "a/b/c/d"))
 XCTAssert(function("a/**/*", "a/b/c/d"))
 XCTAssert(function("a/**/**/*", "a/b/c/d"))
 XCTAssert(function("a/**/**/**/*", "a/b/c/d"))
 XCTAssert(function("a/b/**/c/**/*.*", "a/b/c/d.e"))
 XCTAssert(function("a/**/f/*.md", "a/b/c/d/e/f/g.md"))
 XCTAssert(function("a/**/f/**/k/*.md", "a/b/c/d/e/f/g/h/i/j/k/l.md"))
 XCTAssert(function("a/b/c/*.md", "a/b/c/def.md"))
 XCTAssert(function("a/*/c/*.md", "a/bb.bb/c/ddd.md"))
 XCTAssert(function("a/**/f/*.md", "a/bb.bb/cc/d.d/ee/f/ggg.md"))
 XCTAssert(function("a/**/f/*.md", "a/bb.bb/cc/dd/ee/f/ggg.md"))
 XCTAssert(function("a/*/c/*.md", "a/bb/c/ddd.md"))
 XCTAssert(function("a/*/c/*.md", "a/bbbb/c/ddd.md"))

 XCTAssert(function("foo/bar/**/one/**/*.*", "foo/bar/baz/one/image.png"))
 XCTAssert(function("foo/bar/**/one/**/*.*", "foo/bar/baz/one/two/image.png"))
 XCTAssert(function("foo/bar/**/one/**/*.*", "foo/bar/baz/one/two/three/image.png"))

 XCTAssert(!function("a/b/**/f", "a/b/c/d/"))
 //  XCTAssert(function("a/**", "a"))
 XCTAssert(function("**", "a"))
 //  XCTAssert(function("a{,/**}", "a"))
 XCTAssert(function("**", "a/"))
 XCTAssert(function("a/**", "a/"))
 XCTAssert(function("**", "a/b/c/d"))
 XCTAssert(function("**", "a/b/c/d/"))
 XCTAssert(function("**/**", "a/b/c/d/"))
 XCTAssert(function("**/b/**", "a/b/c/d/"))
 XCTAssert(function("a/b/**", "a/b/c/d/"))
 XCTAssert(function("a/b/**/", "a/b/c/d/"))
 XCTAssert(function("a/b/**/c/**/", "a/b/c/d/"))
 XCTAssert(function("a/b/**/c/**/d/", "a/b/c/d/"))
 XCTAssert(function("a/b/**/**/*.*", "a/b/c/d/e.f"))
 XCTAssert(function("a/b/**/*.*", "a/b/c/d/e.f"))
 XCTAssert(function("a/b/**/c/**/d/*.*", "a/b/c/d/e.f"))
 XCTAssert(function("a/b/**/d/**/*.*", "a/b/c/d/e.f"))
 XCTAssert(function("a/b/**/d/**/*.*", "a/b/c/d/g/e.f"))
 XCTAssert(function("a/b/**/d/**/*.*", "a/b/c/d/g/g/e.f"))
 XCTAssert(function("a/b-*/**/z.js", "a/b-c/z.js"))
 XCTAssert(function("a/b-*/**/z.js", "a/b-c/d/e/z.js"))

 XCTAssert(function("*/*", "a/b"))
 XCTAssert(function("a/b/c/*.md", "a/b/c/xyz.md"))
 XCTAssert(function("a/*/c/*.md", "a/bb.bb/c/xyz.md"))
 XCTAssert(function("a/*/c/*.md", "a/bb/c/xyz.md"))
 XCTAssert(function("a/*/c/*.md", "a/bbbb/c/xyz.md"))

 XCTAssert(function("**/*", "a/b/c"))
 XCTAssert(function("**/**", "a/b/c"))
 XCTAssert(function("*/**", "a/b/c"))
 XCTAssert(function("a/**/j/**/z/*.md", "a/b/c/d/e/j/n/p/o/z/c.md"))
 XCTAssert(function("a/**/z/*.md", "a/b/c/d/e/z/c.md"))
 XCTAssert(function("a/**/c/*.md", "a/bb.bb/aa/b.b/aa/c/xyz.md"))
 XCTAssert(function("a/**/c/*.md", "a/bb.bb/aa/bb/aa/c/xyz.md"))
 XCTAssert(!function("a/**/j/**/z/*.md", "a/b/c/j/e/z/c.txt"))
 XCTAssert(!function("a/b/**/c{d,e}/**/xyz.md", "a/b/c/xyz.md"))
 XCTAssert(!function("a/b/**/c{d,e}/**/xyz.md", "a/b/d/xyz.md"))
 XCTAssert(!function("a/**/", "a/b"))
 //  XCTAssert(!function("**/*", "a/b/.js/c.txt"))
 XCTAssert(!function("a/**/", "a/b/c/d"))
 XCTAssert(!function("a/**/", "a/bb"))
 XCTAssert(!function("a/**/", "a/cb"))
 XCTAssert(function("/**", "/a/b"))
 XCTAssert(function("**/*", "a.b"))
 XCTAssert(function("**/*", "a.js"))
 XCTAssert(function("**/*.js", "a.js"))
 //  XCTAssert(function("a/**/", "a/"))
 XCTAssert(function("**/*.js", "a/a.js"))
 XCTAssert(function("**/*.js", "a/a/b.js"))
 XCTAssert(function("a/**/b", "a/b"))
 XCTAssert(function("a/**b", "a/b"))
 XCTAssert(function("**/*.md", "a/b.md"))
 XCTAssert(function("**/*", "a/b/c.js"))
 XCTAssert(function("**/*", "a/b/c.txt"))
 XCTAssert(function("a/**/", "a/b/c/d/"))
 XCTAssert(function("**/*", "a/b/c/d/a.js"))
 XCTAssert(function("a/b/**/*.js", "a/b/c/z.js"))
 XCTAssert(function("a/b/**/*.js", "a/b/z.js"))
 XCTAssert(function("**/*", "ab"))
 XCTAssert(function("**/*", "ab/c"))
 XCTAssert(function("**/*", "ab/c/d"))
 XCTAssert(function("**/*", "abc.js"))

 XCTAssert(!function("**/", "a"))
 XCTAssert(!function("**/a/*", "a"))
 XCTAssert(!function("**/a/*/*", "a"))
 XCTAssert(!function("*/a/**", "a"))
 XCTAssert(!function("a/**/*", "a"))
 XCTAssert(!function("a/**/**/*", "a"))
 XCTAssert(!function("**/", "a/b"))
 XCTAssert(!function("**/b/*", "a/b"))
 XCTAssert(!function("**/b/*/*", "a/b"))
 XCTAssert(!function("b/**", "a/b"))
 XCTAssert(!function("**/", "a/b/c"))
 XCTAssert(!function("**/**/b", "a/b/c"))
 XCTAssert(!function("**/b", "a/b/c"))
 XCTAssert(!function("**/b/*/*", "a/b/c"))
 XCTAssert(!function("b/**", "a/b/c"))
 XCTAssert(!function("**/", "a/b/c/d"))
 XCTAssert(!function("**/d/*", "a/b/c/d"))
 XCTAssert(!function("b/**", "a/b/c/d"))
 XCTAssert(function("**", "a"))
 XCTAssert(function("**/**", "a"))
 XCTAssert(function("**/**/*", "a"))
 XCTAssert(function("**/**/a", "a"))
 XCTAssert(function("**/a", "a"))
 //  XCTAssert(function("**/a/**", "a"))
 //  XCTAssert(function("a/**", "a"))
 XCTAssert(function("**", "a/b"))
 XCTAssert(function("**/**", "a/b"))
 XCTAssert(function("**/**/*", "a/b"))
 XCTAssert(function("**/**/b", "a/b"))
 XCTAssert(function("**/b", "a/b"))
 //  XCTAssert(function("**/b/**", "a/b"))
 //  XCTAssert(function("*/b/**", "a/b"))
 XCTAssert(function("a/**", "a/b"))
 XCTAssert(function("a/**/*", "a/b"))
 XCTAssert(function("a/**/**/*", "a/b"))
 XCTAssert(function("**", "a/b/c"))
 XCTAssert(function("**/**", "a/b/c"))
 XCTAssert(function("**/**/*", "a/b/c"))
 XCTAssert(function("**/b/*", "a/b/c"))
 XCTAssert(function("**/b/**", "a/b/c"))
 XCTAssert(function("*/b/**", "a/b/c"))
 XCTAssert(function("a/**", "a/b/c"))
 XCTAssert(function("a/**/*", "a/b/c"))
 XCTAssert(function("a/**/**/*", "a/b/c"))
 XCTAssert(function("**", "a/b/c/d"))
 XCTAssert(function("**/**", "a/b/c/d"))
 XCTAssert(function("**/**/*", "a/b/c/d"))
 XCTAssert(function("**/**/d", "a/b/c/d"))
 XCTAssert(function("**/b/**", "a/b/c/d"))
 XCTAssert(function("**/b/*/*", "a/b/c/d"))
 XCTAssert(function("**/d", "a/b/c/d"))
 XCTAssert(function("*/b/**", "a/b/c/d"))
 XCTAssert(function("a/**", "a/b/c/d"))
 XCTAssert(function("a/**/*", "a/b/c/d"))
 XCTAssert(function("a/**/**/*", "a/b/c/d"))

 // utf8
 XCTAssert(function("フ*/**/*", "フォルダ/aaa.js"))
 XCTAssert(function("フォ*/**/*", "フォルダ/aaa.js"))
 XCTAssert(function("フォル*/**/*", "フォルダ/aaa.js"))
 XCTAssert(function("フ*ル*/**/*", "フォルダ/aaa.js"))
 XCTAssert(function("フォルダ/**/*", "フォルダ/aaa.js"))

 // negation
 XCTAssert(!function("!*", "abc"))
 XCTAssert(!function("!abc", "abc"))
 XCTAssert(!function("*!.md", "bar.md"))
 XCTAssert(!function("foo!.md", "bar.md"))
 XCTAssert(!function("\\!*!*.md", "foo!.md"))
 XCTAssert(!function("\\!*!*.md", "foo!bar.md"))
 XCTAssert(function("*!*.md", "!foo!.md"))
 XCTAssert(function("\\!*!*.md", "!foo!.md"))
 XCTAssert(function("!*foo", "abc"))
 XCTAssert(function("!foo*", "abc"))
 XCTAssert(function("!xyz", "abc"))
 XCTAssert(function("*!*.*", "ba!r.js"))
 XCTAssert(function("*.md", "bar.md"))
 XCTAssert(function("*!*.*", "foo!.md"))
 XCTAssert(function("*!*.md", "foo!.md"))
 XCTAssert(function("*!.md", "foo!.md"))
 XCTAssert(function("*.md", "foo!.md"))
 XCTAssert(function("foo!.md", "foo!.md"))
 XCTAssert(function("*!*.md", "foo!bar.md"))
 XCTAssert(function("*b*.md", "foobar.md"))

 XCTAssert(!function("a!!b", "a"))
 XCTAssert(!function("a!!b", "aa"))
 XCTAssert(!function("a!!b", "a/b"))
 XCTAssert(!function("a!!b", "a!b"))
 XCTAssert(function("a!!b", "a!!b"))
 XCTAssert(!function("a!!b", "a/!!/b"))

 XCTAssert(!function("!a/b", "a/b"))
 XCTAssert(function("!a/b", "a"))
 XCTAssert(function("!a/b", "a.b"))
 XCTAssert(function("!a/b", "a/a"))
 XCTAssert(function("!a/b", "a/c"))
 XCTAssert(function("!a/b", "b/a"))
 XCTAssert(function("!a/b", "b/b"))
 XCTAssert(function("!a/b", "b/c"))

 XCTAssert(!function("!abc", "abc"))
 XCTAssert(function("!!abc", "abc"))
 XCTAssert(!function("!!!abc", "abc"))
 XCTAssert(function("!!!!abc", "abc"))
 XCTAssert(!function("!!!!!abc", "abc"))
 XCTAssert(function("!!!!!!abc", "abc"))
 XCTAssert(!function("!!!!!!!abc", "abc"))
 XCTAssert(function("!!!!!!!!abc", "abc"))

 //  XCTAssert(!function("!(*/*)", "a/a"))
 //  XCTAssert(!function("!(*/*)", "a/b"))
 //  XCTAssert(!function("!(*/*)", "a/c"))
 //  XCTAssert(!function("!(*/*)", "b/a"))
 //  XCTAssert(!function("!(*/*)", "b/b"))
 //  XCTAssert(!function("!(*/*)", "b/c"))
 //  XCTAssert(!function("!(*/b)", "a/b"))
 //  XCTAssert(!function("!(*/b)", "b/b"))
 //  XCTAssert(!function("!(a/b)", "a/b"))
 XCTAssert(!function("!*", "a"))
 XCTAssert(!function("!*", "a.b"))
 XCTAssert(!function("!*/*", "a/a"))
 XCTAssert(!function("!*/*", "a/b"))
 XCTAssert(!function("!*/*", "a/c"))
 XCTAssert(!function("!*/*", "b/a"))
 XCTAssert(!function("!*/*", "b/b"))
 XCTAssert(!function("!*/*", "b/c"))
 XCTAssert(!function("!*/b", "a/b"))
 XCTAssert(!function("!*/b", "b/b"))
 XCTAssert(!function("!*/c", "a/c"))
 XCTAssert(!function("!*/c", "a/c"))
 XCTAssert(!function("!*/c", "b/c"))
 XCTAssert(!function("!*/c", "b/c"))
 XCTAssert(!function("!*a*", "bar"))
 XCTAssert(!function("!*a*", "fab"))
 //  XCTAssert(!function("!a/(*)", "a/a"))
 //  XCTAssert(!function("!a/(*)", "a/b"))
 //  XCTAssert(!function("!a/(*)", "a/c"))
 //  XCTAssert(!function("!a/(b)", "a/b"))
 XCTAssert(!function("!a/*", "a/a"))
 XCTAssert(!function("!a/*", "a/b"))
 XCTAssert(!function("!a/*", "a/c"))
 XCTAssert(!function("!f*b", "fab"))
 //  XCTAssert(function("!(*/*)", "a"))
 //  XCTAssert(function("!(*/*)", "a.b"))
 //  XCTAssert(function("!(*/b)", "a"))
 //  XCTAssert(function("!(*/b)", "a.b"))
 //  XCTAssert(function("!(*/b)", "a/a"))
 //  XCTAssert(function("!(*/b)", "a/c"))
 //  XCTAssert(function("!(*/b)", "b/a"))
 //  XCTAssert(function("!(*/b)", "b/c"))
 //  XCTAssert(function("!(a/b)", "a"))
 //  XCTAssert(function("!(a/b)", "a.b"))
 //  XCTAssert(function("!(a/b)", "a/a"))
 //  XCTAssert(function("!(a/b)", "a/c"))
 //  XCTAssert(function("!(a/b)", "b/a"))
 //  XCTAssert(function("!(a/b)", "b/b"))
 //  XCTAssert(function("!(a/b)", "b/c"))
 XCTAssert(function("!*", "a/a"))
 XCTAssert(function("!*", "a/b"))
 XCTAssert(function("!*", "a/c"))
 XCTAssert(function("!*", "b/a"))
 XCTAssert(function("!*", "b/b"))
 XCTAssert(function("!*", "b/c"))
 XCTAssert(function("!*/*", "a"))
 XCTAssert(function("!*/*", "a.b"))
 XCTAssert(function("!*/b", "a"))
 XCTAssert(function("!*/b", "a.b"))
 XCTAssert(function("!*/b", "a/a"))
 XCTAssert(function("!*/b", "a/c"))
 XCTAssert(function("!*/b", "b/a"))
 XCTAssert(function("!*/b", "b/c"))
 XCTAssert(function("!*/c", "a"))
 XCTAssert(function("!*/c", "a.b"))
 XCTAssert(function("!*/c", "a/a"))
 XCTAssert(function("!*/c", "a/b"))
 XCTAssert(function("!*/c", "b/a"))
 XCTAssert(function("!*/c", "b/b"))
 XCTAssert(function("!*a*", "foo"))
 //  XCTAssert(function("!a/(*)", "a"))
 //  XCTAssert(function("!a/(*)", "a.b"))
 //  XCTAssert(function("!a/(*)", "b/a"))
 //  XCTAssert(function("!a/(*)", "b/b"))
 //  XCTAssert(function("!a/(*)", "b/c"))
 //  XCTAssert(function("!a/(b)", "a"))
 //  XCTAssert(function("!a/(b)", "a.b"))
 //  XCTAssert(function("!a/(b)", "a/a"))
 //  XCTAssert(function("!a/(b)", "a/c"))
 //  XCTAssert(function("!a/(b)", "b/a"))
 //  XCTAssert(function("!a/(b)", "b/b"))
 //  XCTAssert(function("!a/(b)", "b/c"))
 XCTAssert(function("!a/*", "a"))
 XCTAssert(function("!a/*", "a.b"))
 XCTAssert(function("!a/*", "b/a"))
 XCTAssert(function("!a/*", "b/b"))
 XCTAssert(function("!a/*", "b/c"))
 XCTAssert(function("!f*b", "bar"))
 XCTAssert(function("!f*b", "foo"))

 XCTAssert(!function("!.md", ".md"))
 XCTAssert(function("!**/*.md", "a.js"))
 XCTAssert(!function("!**/*.md", "b.md"))
 XCTAssert(function("!**/*.md", "c.txt"))
 XCTAssert(function("!*.md", "a.js"))
 XCTAssert(!function("!*.md", "b.md"))
 XCTAssert(function("!*.md", "c.txt"))
 XCTAssert(!function("!*.md", "abc.md"))
 XCTAssert(function("!*.md", "abc.txt"))
 XCTAssert(!function("!*.md", "foo.md"))
 XCTAssert(function("!.md", "foo.md"))

 XCTAssert(function("!*.md", "a.js"))
 XCTAssert(function("!*.md", "b.txt"))
 XCTAssert(!function("!*.md", "c.md"))
 XCTAssert(!function("!a/*/a.js", "a/a/a.js"))
 XCTAssert(!function("!a/*/a.js", "a/b/a.js"))
 XCTAssert(!function("!a/*/a.js", "a/c/a.js"))
 XCTAssert(!function("!a/*/*/a.js", "a/a/a/a.js"))
 XCTAssert(function("!a/*/*/a.js", "b/a/b/a.js"))
 XCTAssert(function("!a/*/*/a.js", "c/a/c/a.js"))
 XCTAssert(!function("!a/a*.txt", "a/a.txt"))
 XCTAssert(function("!a/a*.txt", "a/b.txt"))
 XCTAssert(function("!a/a*.txt", "a/c.txt"))
 XCTAssert(!function("!a.a*.txt", "a.a.txt"))
 XCTAssert(function("!a.a*.txt", "a.b.txt"))
 XCTAssert(function("!a.a*.txt", "a.c.txt"))
 XCTAssert(!function("!a/*.txt", "a/a.txt"))
 XCTAssert(!function("!a/*.txt", "a/b.txt"))
 XCTAssert(!function("!a/*.txt", "a/c.txt"))

 XCTAssert(function("!*.md", "a.js"))
 XCTAssert(function("!*.md", "b.txt"))
 XCTAssert(!function("!*.md", "c.md"))
 //  XCTAssert(!function("!**/a.js", "a/a/a.js"))
 //  XCTAssert(!function("!**/a.js", "a/b/a.js"))
 //  XCTAssert(!function("!**/a.js", "a/c/a.js"))
 XCTAssert(function("!**/a.js", "a/a/b.js"))
 XCTAssert(!function("!a/**/a.js", "a/a/a/a.js"))
 XCTAssert(function("!a/**/a.js", "b/a/b/a.js"))
 XCTAssert(function("!a/**/a.js", "c/a/c/a.js"))
 XCTAssert(function("!**/*.md", "a/b.js"))
 XCTAssert(function("!**/*.md", "a.js"))
 XCTAssert(!function("!**/*.md", "a/b.md"))
 //  XCTAssert(!function("!**/*.md", "a.md"))
 XCTAssert(!function("**/*.md", "a/b.js"))
 XCTAssert(!function("**/*.md", "a.js"))
 XCTAssert(function("**/*.md", "a/b.md"))
 XCTAssert(function("**/*.md", "a.md"))
 XCTAssert(function("!**/*.md", "a/b.js"))
 XCTAssert(function("!**/*.md", "a.js"))
 XCTAssert(!function("!**/*.md", "a/b.md"))
 //  XCTAssert(!function("!**/*.md", "a.md"))
 XCTAssert(function("!*.md", "a/b.js"))
 XCTAssert(function("!*.md", "a.js"))
 XCTAssert(function("!*.md", "a/b.md"))
 XCTAssert(!function("!*.md", "a.md"))
 XCTAssert(function("!**/*.md", "a.js"))
 //  XCTAssert(!function("!**/*.md", "b.md"))
 XCTAssert(function("!**/*.md", "c.txt"))

 // question mark
 XCTAssert(function("?", "a"))
 XCTAssert(!function("?", "aa"))
 XCTAssert(!function("?", "ab"))
 XCTAssert(!function("?", "aaa"))
 XCTAssert(!function("?", "abcdefg"))

 XCTAssert(!function("??", "a"))
 XCTAssert(function("??", "aa"))
 XCTAssert(function("??", "ab"))
 XCTAssert(!function("??", "aaa"))
 XCTAssert(!function("??", "abcdefg"))

 XCTAssert(!function("???", "a"))
 XCTAssert(!function("???", "aa"))
 XCTAssert(!function("???", "ab"))
 XCTAssert(function("???", "aaa"))
 XCTAssert(!function("???", "abcdefg"))

 XCTAssert(!function("a?c", "aaa"))
 XCTAssert(function("a?c", "aac"))
 XCTAssert(function("a?c", "abc"))
 XCTAssert(!function("ab?", "a"))
 XCTAssert(!function("ab?", "aa"))
 XCTAssert(!function("ab?", "ab"))
 XCTAssert(!function("ab?", "ac"))
 XCTAssert(!function("ab?", "abcd"))
 XCTAssert(!function("ab?", "abbb"))
 XCTAssert(function("a?b", "acb"))

 XCTAssert(!function("a/?/c/?/e.md", "a/bb/c/dd/e.md"))
 XCTAssert(function("a/??/c/??/e.md", "a/bb/c/dd/e.md"))
 XCTAssert(!function("a/??/c.md", "a/bbb/c.md"))
 XCTAssert(function("a/?/c.md", "a/b/c.md"))
 XCTAssert(function("a/?/c/?/e.md", "a/b/c/d/e.md"))
 XCTAssert(!function("a/?/c/???/e.md", "a/b/c/d/e.md"))
 XCTAssert(function("a/?/c/???/e.md", "a/b/c/zzz/e.md"))
 XCTAssert(!function("a/?/c.md", "a/bb/c.md"))
 XCTAssert(function("a/??/c.md", "a/bb/c.md"))
 XCTAssert(function("a/???/c.md", "a/bbb/c.md"))
 XCTAssert(function("a/????/c.md", "a/bbbb/c.md"))

 // braces
 XCTAssert(function("{a,b,c}", "a"))
 XCTAssert(function("{a,b,c}", "b"))
 XCTAssert(function("{a,b,c}", "c"))
 XCTAssert(!function("{a,b,c}", "aa"))
 XCTAssert(!function("{a,b,c}", "bb"))
 XCTAssert(!function("{a,b,c}", "cc"))

 XCTAssert(function("a/{a,b}", "a/a"))
 XCTAssert(function("a/{a,b}", "a/b"))
 XCTAssert(!function("a/{a,b}", "a/c"))
 XCTAssert(!function("a/{a,b}", "b/b"))
 XCTAssert(!function("a/{a,b,c}", "b/b"))
 XCTAssert(function("a/{a,b,c}", "a/c"))
 XCTAssert(function("a{b,bc}.txt", "abc.txt"))

 XCTAssert(function("foo[{a,b}]baz", "foo{baz"))

 XCTAssert(!function("a{,b}.txt", "abc.txt"))
 XCTAssert(!function("a{a,b,}.txt", "abc.txt"))
 XCTAssert(!function("a{b,}.txt", "abc.txt"))
 XCTAssert(function("a{,b}.txt", "a.txt"))
 XCTAssert(function("a{b,}.txt", "a.txt"))
 XCTAssert(function("a{a,b,}.txt", "aa.txt"))
 XCTAssert(function("a{a,b,}.txt", "aa.txt"))
 XCTAssert(function("a{,b}.txt", "ab.txt"))
 XCTAssert(function("a{b,}.txt", "ab.txt"))

 //  XCTAssert(function("{a/,}a/**", "a"))
 XCTAssert(function("a{a,b/}*.txt", "aa.txt"))
 XCTAssert(function("a{a,b/}*.txt", "ab/.txt"))
 XCTAssert(function("a{a,b/}*.txt", "ab/a.txt"))
 //  XCTAssert(function("{a/,}a/**", "a/"))
 XCTAssert(function("{a/,}a/**", "a/a/"))
 //  XCTAssert(function("{a/,}a/**", "a/a"))
 XCTAssert(function("{a/,}a/**", "a/a/a"))
 XCTAssert(function("{a/,}a/**", "a/a/"))
 XCTAssert(function("{a/,}a/**", "a/a/a/"))
 XCTAssert(function("{a/,}b/**", "a/b/a/"))
 XCTAssert(function("{a/,}b/**", "b/a/"))
 XCTAssert(function("a{,/}*.txt", "a.txt"))
 XCTAssert(function("a{,/}*.txt", "ab.txt"))
 XCTAssert(function("a{,/}*.txt", "a/b.txt"))
 XCTAssert(function("a{,/}*.txt", "a/ab.txt"))

 XCTAssert(function("a{,.*{foo,db},\\(bar\\)}.txt", "a.txt"))
 XCTAssert(!function("a{,.*{foo,db},\\(bar\\)}.txt", "adb.txt"))
 XCTAssert(function("a{,.*{foo,db},\\(bar\\)}.txt", "a.db.txt"))

 XCTAssert(function("a{,*.{foo,db},\\(bar\\)}.txt", "a.txt"))
 XCTAssert(!function("a{,*.{foo,db},\\(bar\\)}.txt", "adb.txt"))
 XCTAssert(function("a{,*.{foo,db},\\(bar\\)}.txt", "a.db.txt"))

 //  XCTAssert(function("a{,.*{foo,db},\\(bar\\)}", "a"))
 XCTAssert(!function("a{,.*{foo,db},\\(bar\\)}", "adb"))
 XCTAssert(function("a{,.*{foo,db},\\(bar\\)}", "a.db"))

 //  XCTAssert(function("a{,*.{foo,db},\\(bar\\)}", "a"))
 XCTAssert(!function("a{,*.{foo,db},\\(bar\\)}", "adb"))
 XCTAssert(function("a{,*.{foo,db},\\(bar\\)}", "a.db"))

 XCTAssert(!function("{,.*{foo,db},\\(bar\\)}", "a"))
 XCTAssert(!function("{,.*{foo,db},\\(bar\\)}", "adb"))
 XCTAssert(!function("{,.*{foo,db},\\(bar\\)}", "a.db"))
 XCTAssert(function("{,.*{foo,db},\\(bar\\)}", ".db"))

 XCTAssert(!function("{,*.{foo,db},\\(bar\\)}", "a"))
 XCTAssert(function("{*,*.{foo,db},\\(bar\\)}", "a"))
 XCTAssert(!function("{,*.{foo,db},\\(bar\\)}", "adb"))
 XCTAssert(function("{,*.{foo,db},\\(bar\\)}", "a.db"))

 XCTAssert(!function("a/b/**/c{d,e}/**/xyz.md", "a/b/c/xyz.md"))
 XCTAssert(!function("a/b/**/c{d,e}/**/xyz.md", "a/b/d/xyz.md"))
 XCTAssert(function("a/b/**/c{d,e}/**/xyz.md", "a/b/cd/xyz.md"))
 XCTAssert(function("a/b/**/{c,d,e}/**/xyz.md", "a/b/c/xyz.md"))
 XCTAssert(function("a/b/**/{c,d,e}/**/xyz.md", "a/b/d/xyz.md"))
 XCTAssert(function("a/b/**/{c,d,e}/**/xyz.md", "a/b/e/xyz.md"))

 XCTAssert(function("*{a,b}*", "xax"))
 XCTAssert(function("*{a,b}*", "xxax"))
 XCTAssert(function("*{a,b}*", "xbx"))

 XCTAssert(function("*{*a,b}", "xba"))
 XCTAssert(function("*{*a,b}", "xb"))

 XCTAssert(!function("*??", "a"))
 XCTAssert(!function("*???", "aa"))
 XCTAssert(function("*???", "aaa"))
 XCTAssert(!function("*****??", "a"))
 XCTAssert(!function("*****???", "aa"))
 XCTAssert(function("*****???", "aaa"))

 XCTAssert(!function("a*?c", "aaa"))
 XCTAssert(function("a*?c", "aac"))
 XCTAssert(function("a*?c", "abc"))

 XCTAssert(function("a**?c", "abc"))
 XCTAssert(!function("a**?c", "abb"))
 XCTAssert(function("a**?c", "acc"))
 XCTAssert(function("a*****?c", "abc"))

 XCTAssert(function("*****?", "a"))
 XCTAssert(function("*****?", "aa"))
 XCTAssert(function("*****?", "abc"))
 XCTAssert(function("*****?", "zzz"))
 XCTAssert(function("*****?", "bbb"))
 XCTAssert(function("*****?", "aaaa"))

 XCTAssert(!function("*****??", "a"))
 XCTAssert(function("*****??", "aa"))
 XCTAssert(function("*****??", "abc"))
 XCTAssert(function("*****??", "zzz"))
 XCTAssert(function("*****??", "bbb"))
 XCTAssert(function("*****??", "aaaa"))

 XCTAssert(!function("?*****??", "a"))
 XCTAssert(!function("?*****??", "aa"))
 XCTAssert(function("?*****??", "abc"))
 XCTAssert(function("?*****??", "zzz"))
 XCTAssert(function("?*****??", "bbb"))
 XCTAssert(function("?*****??", "aaaa"))

 XCTAssert(function("?*****?c", "abc"))
 XCTAssert(!function("?*****?c", "abb"))
 XCTAssert(!function("?*****?c", "zzz"))

 XCTAssert(function("?***?****c", "abc"))
 XCTAssert(!function("?***?****c", "bbb"))
 XCTAssert(!function("?***?****c", "zzz"))

 XCTAssert(function("?***?****?", "abc"))
 XCTAssert(function("?***?****?", "bbb"))
 XCTAssert(function("?***?****?", "zzz"))

 XCTAssert(function("?***?****", "abc"))
 XCTAssert(function("*******c", "abc"))
 XCTAssert(function("*******?", "abc"))
 XCTAssert(function("a*cd**?**??k", "abcdecdhjk"))
 XCTAssert(function("a**?**cd**?**??k", "abcdecdhjk"))
 XCTAssert(function("a**?**cd**?**??k***", "abcdecdhjk"))
 XCTAssert(function("a**?**cd**?**??***k", "abcdecdhjk"))
 XCTAssert(function("a**?**cd**?**??***k**", "abcdecdhjk"))
 XCTAssert(function("a****c**?**??*****", "abcdecdhjk"))

 XCTAssert(!function("a/?/c/?/*/e.md", "a/b/c/d/e.md"))
 XCTAssert(function("a/?/c/?/*/e.md", "a/b/c/d/e/e.md"))
 XCTAssert(function("a/?/c/?/*/e.md", "a/b/c/d/efghijk/e.md"))
 XCTAssert(function("a/?/**/e.md", "a/b/c/d/efghijk/e.md"))
 XCTAssert(!function("a/?/e.md", "a/bb/e.md"))
 XCTAssert(function("a/??/e.md", "a/bb/e.md"))
 XCTAssert(!function("a/?/**/e.md", "a/bb/e.md"))
 XCTAssert(function("a/?/**/e.md", "a/b/ccc/e.md"))
 XCTAssert(function("a/*/?/**/e.md", "a/b/c/d/efghijk/e.md"))
 XCTAssert(function("a/*/?/**/e.md", "a/b/c/d/efgh.ijk/e.md"))
 XCTAssert(function("a/*/?/**/e.md", "a/b.bb/c/d/efgh.ijk/e.md"))
 XCTAssert(function("a/*/?/**/e.md", "a/bbb/c/d/efgh.ijk/e.md"))

 XCTAssert(function("a/*/ab??.md", "a/bbb/abcd.md"))
 XCTAssert(function("a/bbb/ab??.md", "a/bbb/abcd.md"))
 XCTAssert(function("a/bbb/ab???md", "a/bbb/abcd.md"))
}
